"""Serialize extracted schemas into LLM-agent-friendly formats.

Three formats are offered, in decreasing order of recommendation for feeding an
LLM agent:

* **Markdown** (``build_markdown``) — the default. Compact, highly readable, and
  reliably parsed by language models. A context header gives the agent the
  server/database and object inventory, then each object is one section with a
  column table plus its primary and foreign keys.
* **JSON** (``build_json``) — best when another program will consume the output
  before the agent does, or when strict structure matters.
* **SQL DDL** (``build_ddl``) — approximate ``CREATE TABLE`` / ``CREATE VIEW``
  statements, useful when the agent reasons natively in SQL.

Every builder takes the selected :class:`~app.sql_client.TableSchema` objects, so
the UI can export only what the user ticked.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from .fabric_client import SqlEndpoint
from .sql_client import TableSchema

# Format identifiers shared with the UI dropdown.
FORMAT_MARKDOWN = "Markdown (.md)"
FORMAT_JSON = "JSON (.json)"
FORMAT_DDL = "SQL DDL (.sql)"

EXPORT_FORMATS = [FORMAT_MARKDOWN, FORMAT_JSON, FORMAT_DDL]


@dataclass(frozen=True)
class ExportResult:
    """A rendered export ready to preview or download."""

    content: str
    file_name: str
    language: str  # syntax hint for st.code / download mime selection


def export(
    fmt: str,
    endpoint: SqlEndpoint,
    schemas: list[TableSchema],
) -> ExportResult:
    """Render ``schemas`` in the requested format and return an ExportResult."""
    if fmt == FORMAT_JSON:
        return ExportResult(build_json(endpoint, schemas), _file_name(endpoint, "json"), "json")
    if fmt == FORMAT_DDL:
        return ExportResult(build_ddl(endpoint, schemas), _file_name(endpoint, "sql"), "sql")
    return ExportResult(build_markdown(endpoint, schemas), _file_name(endpoint, "md"), "markdown")


def _file_name(endpoint: SqlEndpoint, extension: str) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in endpoint.name)
    return f"{safe or 'schema'}_schema.{extension}"


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_markdown(endpoint: SqlEndpoint, schemas: list[TableSchema]) -> str:
    """Render the selected schemas as a single Markdown document."""
    tables = [s for s in schemas if s.object_type == "TABLE"]
    views = [s for s in schemas if s.object_type == "VIEW"]
    total_columns = sum(len(s.columns) for s in schemas)

    lines: list[str] = []
    lines.append(f"# Database schema: {endpoint.name}")
    lines.append("")
    lines.append("> Schema reference for an LLM agent. Generated by Fabric SQL Explorer.")
    lines.append("")
    lines.append("## Context")
    lines.append("")
    lines.append(f"- **Endpoint:** {endpoint.name} ({endpoint.item_kind})")
    lines.append(f"- **Server:** `{endpoint.server}`")
    lines.append(f"- **Database:** `{endpoint.database}`")
    lines.append(
        f"- **Objects:** {len(tables)} table(s), {len(views)} view(s), "
        f"{total_columns} column(s) total"
    )
    lines.append("")

    inventory = ", ".join(s.full_name for s in schemas) or "(none)"
    lines.append(f"- **Inventory:** {inventory}")
    lines.append("")

    for schema in schemas:
        lines.extend(_markdown_object(schema))

    return "\n".join(lines).rstrip() + "\n"


def _markdown_object(schema: TableSchema) -> list[str]:
    lines: list[str] = []
    lines.append(f"## {schema.full_name}")
    lines.append("")
    lines.append(f"*Type:* {schema.object_type.title()}")
    lines.append("")
    lines.append("| Column | Type | Nullable | Key | Default |")
    lines.append("| --- | --- | --- | --- | --- |")
    for col in schema.columns:
        key = "PK" if col.is_primary_key else ""
        nullable = "yes" if col.is_nullable else "no"
        default = f"`{col.default}`" if col.default else ""
        lines.append(
            f"| {col.name} | {col.type_display} | {nullable} | {key} | {default} |"
        )
    lines.append("")

    if schema.foreign_keys:
        lines.append("**Foreign keys:**")
        lines.append("")
        for fk in schema.foreign_keys:
            lines.append(f"- `{fk.column}` → `{fk.references_full}`")
        lines.append("")

    return lines


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def build_json(endpoint: SqlEndpoint, schemas: list[TableSchema]) -> str:
    """Render the selected schemas as a single JSON document."""
    payload = {
        "endpoint": {
            "name": endpoint.name,
            "kind": endpoint.item_kind,
            "server": endpoint.server,
            "database": endpoint.database,
        },
        "objects": [
            {
                "schema": s.schema,
                "name": s.name,
                "full_name": s.full_name,
                "type": s.object_type,
                "columns": [
                    {
                        "name": c.name,
                        "ordinal": c.ordinal,
                        "type": c.type_display,
                        "data_type": c.data_type,
                        "nullable": c.is_nullable,
                        "primary_key": c.is_primary_key,
                        "default": c.default,
                    }
                    for c in s.columns
                ],
                "foreign_keys": [
                    {
                        "column": fk.column,
                        "references": {
                            "schema": fk.references_schema,
                            "table": fk.references_table,
                            "column": fk.references_column,
                        },
                        "constraint": fk.constraint_name,
                    }
                    for fk in s.foreign_keys
                ],
            }
            for s in schemas
        ],
    }
    return json.dumps(payload, indent=2)


# ---------------------------------------------------------------------------
# SQL DDL (approximate)
# ---------------------------------------------------------------------------


def build_ddl(endpoint: SqlEndpoint, schemas: list[TableSchema]) -> str:
    """Render approximate CREATE statements for the selected schemas."""
    blocks: list[str] = [
        f"-- Approximate DDL for {endpoint.name} ({endpoint.database})",
        f"-- Server: {endpoint.server}",
        "",
    ]
    for schema in schemas:
        if schema.object_type == "VIEW":
            blocks.append(f"-- VIEW {schema.full_name} (definition not retrieved)")
            blocks.append(f"-- CREATE VIEW [{schema.schema}].[{schema.name}] AS ...;")
            blocks.append("")
            continue
        blocks.append(_ddl_table(schema))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _ddl_table(schema: TableSchema) -> str:
    lines = [f"CREATE TABLE [{schema.schema}].[{schema.name}] ("]
    col_defs: list[str] = []
    for col in schema.columns:
        null = "NULL" if col.is_nullable else "NOT NULL"
        default = f" DEFAULT {col.default}" if col.default else ""
        col_defs.append(f"    [{col.name}] {col.type_display} {null}{default}")

    pk_cols = [c.name for c in schema.columns if c.is_primary_key]
    if pk_cols:
        pk_list = ", ".join(f"[{c}]" for c in pk_cols)
        col_defs.append(f"    CONSTRAINT [PK_{schema.name}] PRIMARY KEY ({pk_list})")

    lines.append(",\n".join(col_defs))
    lines.append(");")

    for fk in schema.foreign_keys:
        lines.append(
            f"ALTER TABLE [{schema.schema}].[{schema.name}] "
            f"ADD CONSTRAINT [{fk.constraint_name}] FOREIGN KEY ([{fk.column}]) "
            f"REFERENCES [{fk.references_schema}].[{fk.references_table}] "
            f"([{fk.references_column}]);"
        )
    return "\n".join(lines)
